# Generated by Django 5.1.3 on 2024-11-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=20)),
                ('lastname', models.TextField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('message', models.TextField(default='', max_length=20)),
            ],
        ),
    ]
